### ISSUE TITLE
Расширить конфигурацию ESLint 

### ISSUE THREAD

**Issue by AlexandrKoliukh** [hexlet-components/react-todo-app-with-backend#10]
Базовая конфигурация ESLint, созданная cra, не соответствует hexlet style.

1. Расширить конфигурацию, путем создания отдельного файла формата yaml. 
2. Добавить конфиг airbnb
3. Расширить конфиг для использования с prettier
4. Настроить husky и lint-staged
5. Исправить ошибки кодовой базы

https://create-react-app.dev/docs/setting-up-your-editor#formatting-code-automatically
https://medium.com/@pppped/extend-create-react-app-with-airbnbs-eslint-config-prettier-flow-and-react-testing-library-96627e9a9672

**Comment by alex-ismailov** [comment]
Взял в работу.
