### ISSUE TITLE
Эмуляция бэкэнд

### ISSUE THREAD

**Issue by AlexandrKoliukh** [hexlet-components/react-todo-app-with-backend#11]
В будущем, приложение будет интегрироваться с бэкэндом. Нужно сразу создать слои для работы с api REST

1. Подключить mirage.js
2. Сделать crud для задач
3. Выделить слой для работы с api, использовать axios для запросов
4. Делать без фанатизма и создания классов, просто файл с роутами и стандартный crud mirage

https://miragejs.com/

**Comment by ysemenyuk** [comment]
Взял в работу.
