### ISSUE TITLE
Создать отдельный файл для инициализации приложения.

### ISSUE THREAD

**Issue by alex-ismailov** [hexlet-components/react-todo-app-with-backend#12]
Текущее поведение:
Ининциализация начального состояния приложения происходит при помощи импорта модуля src/slices/index.js в src/index.js
Также не обязательно использовать combineReducers так как configureStore может сделать это за нас.

Ожидаемое поведение:
Все зависимости (rollbar, i18n, store и т.д.) надо заводить в src/index.js, и затем прокидывать их(зависимости) в src/init.js. Задача init.jsx файла вернуть кусок jsx который надо будет рендерить.

**Comment by alex-ismailov** [comment]
Взял в работу.

**Comment by AlexandrKoliukh** [comment]
Можно закрыть

**Comment by alex-ismailov** [comment]
closed.
