### ISSUE TITLE
Санки для запросов

### ISSUE THREAD

**Issue by AlexandrKoliukh** [hexlet-components/react-todo-app-with-backend#13]
Обернуть апишку в createAsyncThunk, сделать подписку в редаксе. https://redux-toolkit.js.org/api/createAsyncThunk

https://github.com/AlexandrKoliukh/redux-boilerplates/blob/master/fetchingStatesSlice.ts
Применить такой патерн для отслеживания состояний запросов

**Comment by ysemenyuk** [comment]
взял в работу.
