### ISSUE TITLE
Лоадеры для асинхронщины

### ISSUE THREAD

**Issue by AlexandrKoliukh** [hexlet-components/react-todo-app-with-backend#15]
Для всех асинхронных действий нужно добавить лоадеры.

В сторе есть thunkStatuses, здесь хранятся статусы всех асинхронных запросов. Как вариант, сделать кастомный хук, который принимает санк, и возвращает его статус

**Comment by frontstall** [comment]
Немного поменялась архитектура, локальный стейт перенёс в компоненты. Добавил блокировку инпутов и кнопок на время запросов, **можно ещё добавить лоадеры из бутстрапа**, простая задачка.

**Comment by YU-K** [comment]
Парни, я добавлю лоадеры.

**Comment by YU-K** [comment]
Предлагаю добавления тасков и получение списка тасков выделить в отдельное состояние ('loadingProcess'), так как это отдельный процесс. И к нему уже цеплять лоудеры.

**Comment by YU-K** [comment]
1. Сейчас компонент TasksList рендерится при инициализации приложения, хотя он пустой. 
2. В TasksList добавляются пустые таски.

**Comment by frontstall** [comment]
> 1. Сейчас компонент TasksList рендерится при инициализации приложения, хотя он пустой.
> 2. В TasksList добавляются пустые таски.

это в ишьи

**Comment by frontstall** [comment]
> Предлагаю добавления тасков и получение списка тасков выделить в отдельное состояние ('loadingProcess'), так как это отдельный процесс. И к нему уже цеплять лоудеры.

список тасков приходит вместе со страницей в гоне, там нет загрузки. Добавление таска имеет состояние isSubmitting (управляется formik'ом):
https://github.com/hexlet-components/react-todo-app-with-backend/blob/60a2c3f285f6e07d66bee1b1cfcc73a689c6b50d/src/features/tasks/NewTaskForm.jsx#L49

Удаление таска тоже имеет состояние:
https://github.com/hexlet-components/react-todo-app-with-backend/blob/60a2c3f285f6e07d66bee1b1cfcc73a689c6b50d/src/features/tasks/Task.jsx#L17

**Comment by frontstall** [comment]
@YU-K получается? Помощь нужна?

**Comment by VladimirAfanasievFS** [comment]
> > 1. Сейчас компонент TasksList рендерится при инициализации приложения, хотя он пустой.
> > 2. В TasksList добавляются пустые таски.
> 
> это в ишьи

https://github.com/AlexandrKoliukh/react-todo-app-with-backend/pull/9

**Comment by YU-K** [comment]
> @YU-K получается? Помощь нужна?
Чуть отвлекся на другие задачи, постараюсь на этой неделе добить

**Comment by YU-K** [comment]
@frontstall Чуть на другие задачи переключился, постараюсь на этой неделе добить.

**Comment by bondiano** [comment]
Я возьму

**Comment by AlexandrKoliukh** [comment]
@bondiano https://github.com/AlexandrKoliukh/react-todo-app-with-backend/pull/12 разберись плиз чего тут. Уже кто-то начинал делать

**Comment by bondiano** [comment]
Охота эти моменты сделать для интенсива по тестированию, @YU-K, как твой прогресс? Если что создавай ПР в эту репку, быстро глянем, что накинем еще на ПР)

**Comment by YU-K** [comment]
Доделаю на этой неделе

**Comment by bondiano** [comment]
@YU-K, привет, доделал спинеры? Сделаешь ПР?

**Comment by YU-K** [comment]
Привет доделал.

**Comment by AlexandrKoliukh** [comment]
@YU-K Перенеси свой коммит на форк от основной репы. Мой форк довольно сильно отстал, я его закрою. Не знаю уже где актуальные изменения где нет.

**Comment by frontstall** [comment]
https://github.com/hexlet-components/react-todo-app-with-backend/pull/26
