### ISSUE TITLE
Использовать i18n для текстов

### ISSUE THREAD

**Issue by fey** [hexlet-components/react-todo-app-with-backend#18]
В данный момент по тексту размазаны тексты. Сам текст только в 1 локали.
Пример
```
$ git grep placeholder
src/features/lists/NewListForm.jsx:              placeholder="List name..."
src/features/tasks/NewTaskForm.jsx:                placeholder="Please type text..."
```
https://github.com/AlexandrKoliukh/react-todo-app-with-backend

Кажется хорошей идеей сделать все интерфейсные тексты через i18n.

**Comment by Surtt** [comment]
Попробую сделать этот ишью

**Comment by fey** [comment]
Решили не делать
