### ISSUE TITLE
Завершённая задача должна опускаться вниз

### ISSUE THREAD

**Issue by Melodyn** [hexlet-components/react-todo-app-with-backend#8]
Текущее поведение: 
Завершённая задача зачёркивается, но остаётся в том же положении в списке задач

Ожидаемое поведение:
Завершённая задача зачёркивается и перемещается вниз. При повторном клие на завершённую задачу - возвращается наверх. Сортировка задач при этом не должна нарушаться.

**Comment by letzabelin** [comment]
> При повторном клике возвращается наверх

Совсем наверх или на прежнее место?

**Comment by Melodyn** [comment]
Давай набросаю кейсом, как примерно должно быть. Берём список задач:
1 2 3 4 5

Зачёркиваем сначала четвёртую, потом вторую:
1 2 3 5 ~4~
1 2 5 ~2~ ~4~

Потом щёлкаем по четвёртой повторно:
1 3 4 5 ~2~

Потом щёлкаем по первой:
3 4 5 ~1~ ~2~

То есть они сохраняют сортировку и при выполненном состоянии, и при обычном.

**Comment by letzabelin** [comment]
Понял, тогда беру задачу

**Comment by Melodyn** [comment]
Отлично. Есть ещё такой баг, что при быстром клике по чекбоксам, можно поймать пролаг, когда задача становится зачёркнутой и при отпущенном чекбоксе и вычёркивается при заполненном. Если что, Саша Колиух видел этот баг, можешь у него уточнить, если сам не разберёшься.

**Comment by letzabelin** [comment]
да, Саша сказал, что уже разбираются с этим. Задача закрыта

**Comment by AlexandrKoliukh** [comment]
Можно закрыть
