### ISSUE TITLE
Добавить список списков задач

### ISSUE THREAD

**Issue by Melodyn** [hexlet-components/react-todo-app-with-backend#9]
Сделать возможность добавлять несколько списков, каждый из которых будт содержать собственный список задач.

Надо иметь в виду, что позже будет подключен бэкенд к этому приложению, поэтому текущая архитектура создания и получения задач и списков задач должна быть подготовлена к типовому REST API.

**Comment by frontstall** [comment]
UPD:

бекенд добавлен, есть два дефолтных списка на старте для удобства разработки. Один удаляемый и один, дефолтный, не удаляемый. Нужно добавить возможность создавать списки.

**Comment by ysemenyuk** [comment]
я могу попробовать, есть какой-то примерный дизайн как должно выглядеть? и как получается с тасками, они все к нам изначально приходят, для всех каналов? а при выборе канала выводим только для текущего?

**Comment by frontstall** [comment]
Можно подсмотреть, например, в https://todoist.com/
Структуру того, в каком виде приходят данные, можно увидеть в коде серверной части или набрав в консоли разработчика в браузере `gon`
При выборе списка показываем таски только для него. При добавлении таска указываем айдишник текущего списка. В общем, всё как в четвёртом проекте по фронту)

**Comment by frontstall** [comment]
ещё по дизайну: используем бутстрап 5 без кастомных стилей

**Comment by frontstall** [comment]
@ysemenyuk как успехи? Помощь нужна?

**Comment by ysemenyuk** [comment]
https://github.com/AlexandrKoliukh/react-todo-app-with-backend/tree/master/src/features/lists
